# Stage 1 (Builder Stage) - Used to build the packages and app

FROM node:24 AS builder

# Creates a folder and makes it as pwd

WORKDIR /app

# Copies code from the host machine to the container

COPY . .

# Install packages and dependencies

RUN npm install --legacy-peer-deps

# Create a folder /dist (compressed distribution)

RUN npm run build


# Stage 2 (Runner Stage) - Used to run the application from the builder stage

FROM node:24-alpine AS runner

WORKDIR /app

COPY package.json .

RUN npm install -g vite

COPY --from=builder /app/dist ./dist

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]


